### ISSUE TITLE
Send Leave Request

### ISSUE THREAD

**Issue by galmok** [mdeweerd/zha-toolkit#228]
I am using the latest version of ZHA Toolkit, and while trying to make one of my devices work again (it dropped out), I tried to use ZHA Toolkit to make the coordinator forget about the device so I could attempt a new clean join.

But the "Send Leave Request" requires a parameter, "Node to send the Rejoin" which is mandatory, and I have no idea what to put there. 

Could this be an error with this request?

**Comment by mdeweerd** [comment]
The "Send Leave Request" is a message sent from the coordinator (ZHA) to a device to request that it leaves the network.

End devices and routers keep information about the network they belong to and this request tells them to erase this information so that they no longer belong to the network.

When successful (i.e. normal operation), the device will notify the network that it leaves the network which results in the coordinator (ZHA) also "forgetting" (mostly) about it.

A rejoin command will ask that a device leaves the network, but that it immediately tries to join the network again.  This is useful if you want to proceed with some level of re-initialisation without starting the join process manually on the device.

When the device is already no longer in the network, this will not work.

So ZHA needs to know where to send this request meaning it needs an identification of the device (the ieee addres here).


You can also delete the device from ZHA (which should also send a leave request) and/or perform a reset on the device (usually a long press on a button brings the device to factory settings);
