### ISSUE TITLE
Unstable ZigBee Behavior

### ISSUE THREAD

**Issue by AlexW75** [mdeweerd/zha-toolkit#230]
Since 2024.06, I've noticed that all my ZigBee devices frequently disconnect (about every 8 hours). After approximately 10-20 seconds, the devices reconnect.

However, if I disable the ZHA toolkit, this issue disappears, and my ZigBee network remains 100% stable without any device drops.

Is anyone else experiencing the same problem? Please check your logs.
I can provide debug data if needed.

**Comment by BenchPressesBooks** [comment]
Funny enough I have noticed this with literally every single one of my Ikea window and door sensors direct connected to a zigbee dongle. The devices never report the stable state (always closed), or the state changes (when you open or close the door. It appears every 12 or 24 hours roughly they become unavailable, then around 2 hours later they come back with a wrong state being reported. If I disable zha-toolkit and restart home assistant they seem to start reporting correctly.

```
June 12, 2024
was opened
11:48:22 AM - Yesterday
became unavailable
9:32:57 AM - Yesterday
June 11, 2024
was opened
11:35:59 PM - 2 days ago
became unavailable
9:35:45 PM - 2 days ago
was opened
10:28:38 AM - 2 days ago
became unavailable
8:14:04 AM - 2 days ago
June 10, 2024
was opened
9:51:01 PM - 3 days ago
became unavailable
7:39:23 AM - 3 days ago
```

Turning on debug logging returns nothing related to this that hasn't already been reported in issue #229, #227 , and #231 . I am still investigating but am coming up empty handed for now.

**Comment by AlexW75** [comment]
Did the same … switched on logging - nothing related.

Checked the ZigBee communication - also there nothing unusual. The problem must occur inside ZHA when ZHA-Toolkit is active.

**Comment by CordoWEB** [comment]
I noticed the same problem.
I'm going back to version 2024.5.5 to see what happens.

**Comment by AlexW75** [comment]
Thanks for the info … in my case I have no dropped devices since I uninstalled the toolkit.

**Comment by BenchPressesBooks** [comment]
Just wanted to report that with the latest zha update everything is perfectly stable with the network at least. Still have the blocking call and other issues but the device unavailable then fine issue seems to be gone. Had one device with lingering issues but after removing and reading it the issue went away as well. This one may be able to be closed seeing that the oarentkzha seems to have been where the issue was.

**Comment by mdeweerd** [comment]
Some incompatibilities with the recent versions were introduced by HA changes.
Possibly this had some impact on the behavior, but normally it should not because zha-toolkit is not intrusive in zha except when using a zha-toolkit service.

I am closing this as the pull requests are now in the official release and the information in this issue does not help identify a problem in zha-toolkit.

If the issue persists with the update, try to find errors in the log that involve zha-toolkit to help identify a potential issue.
