### ISSUE TITLE
attr_read: AttributeError: 'NoneType' object has no attribute 'aps_data_request'

### ISSUE THREAD

**Issue by lelmarir** [mdeweerd/zha-toolkit#88]
executing this service call:
```
service: zha_toolkit.execute
data:
  command: attr_read
  ieee: 28:6d:97:00:01:12:aa:33
  cluster: 0xfc02
  attribute: 0x0000
  manf: 4673
```
i get this error:
```
2022-09-14 22:08:27.900 DEBUG (MainThread) [custom_components.zha_toolkit] event_data {'zha_toolkit_version': 'v0.8.16', 'zigpy_version': '0.50.3', 'zigpy_rf_version': None, 'ieee_org': 28:6d:97:00:01:12:aa:33, 'ieee': '28:6d:97:00:01:12:aa:33', 'command': 'attr_read', 'command_data': None, 'start_time': '2022-09-14T20:08:27.882539+00:00', 'errors': ['AttributeError("\'NoneType\' object has no attribute \'aps_data_request\'")'], 'params': {'cluster_id': 0, 'attr_id': 4, 'dir': 0, 'manf': 18035, 'tries': 1, 'expect_reply': True, 'args': [], 'read_before_write': True, 'read_after_write': True}, 'success': False}
2022-09-14 22:08:27.903 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'NoneType' object has no attribute 'aps_data_request'
```
any idea why?

here the full log and a scan of this device
[error.log](https://github.com/mdeweerd/zha-toolkit/files/9569652/error.log)
[multi_Samjin_000112aa33_scan_results-txt.json.txt](https://github.com/mdeweerd/zha-toolkit/files/9569653/multi_Samjin_000112aa33_scan_results-txt.json.txt)

**Comment by mdeweerd** [comment]
Probabably not the reason, but deconz api/radio detection by zha-toolkit seems not complete.
I added some debug information to >=0.8.17 (not released in any way) where it will read "Did not recognize _api '...'" to have more information about what to look for.  
However detection in itself might be ok.  

The following hints that the internal _api variable of deconz is set to "None":
``` 
File "/usr/local/lib/python3.10/site-packages/zigpy_deconz/zigbee/application.py", line 509, in request
await self._api.aps_data_request(
AttributeError: 'NoneType' object has no attribute 'aps_data_request'
```

That shows that 'aps_data_request' is called on a None, which means that _api in zigpy_deconz is None.
 https://github.com/zigpy/zigpy-deconz/blob/dev/zigpy_deconz/zigbee/application.py#L90-L94

Which is strange because you succeeded a scan of the device at some point

So does that mean that zigpy_deconz suddenly got unconfigured/reset/... ?.


IMHO, deconz can not be functionnal if it has _api set to None, which suggests its not initialized at that point.
The "scan_device' run was clearly able to read the attributes, and scan_device and attr_read use the same method.  Si if one works, so should t he other.

You could try to do the scan_device again after your failing read to at least see if it is related or not to deconz's actual availability.

**Comment by lelmarir** [comment]
A reboot has indeed fixed the problem, now i'ts working like a charm. I'll keep it monitored, thank you

**Comment by MattWestb** [comment]
I see 2 problems with scan network.
- 1 its not allowed in Zigbee 3 doing in one active network then its braking the active routing in the mesh (Silabs have taking away automatic scans in there Zigbee stack).
- 2 It can being that the NCP need being retested after doing the scan for going back to normal working mode (all things is not documented in the deCONZ protocol) and its not implanted in the deCONZ lib and only way is doing one new start of ZHA.

**Comment by mdeweerd** [comment]
@lelmarir Thank you for the followup.
@MattWestb It is not clear at all that a scan_network broke things.   The ApplicationController._app was None - one could ask when that can happen - at least on start up, but is it set to None somewhere after it has been initialised?  Also, when that attribute is None, maybe Deconz could try to reinitialize.  Now that all is something to be discussed at https://github.com/zigpy/zigpy-deconz/issues .
